// Generated by CoffeeScript 1.6.1
(function() {
  var engine, lexer, parse;

  lexer = require('./lexer');

  parse = require('./parser');

  engine = require('./engine');

  module.exports = {
    tumble: lexer.parse,
    parse: parse,
    render: function(str, data) {
      return parse(lexer.parse(str), data);
    },
    engine: engine
  };

}).call(this);
